/*
 * Introduction to Jakarta Enterprise Edition - JPA on Hibernate
 * 
 * https://github.com/egalli64/jeed
 */
package com.example.jeed.dao;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.SequenceGenerator;

/**
 * JPA entity for CAR in an optional one to one relation with EMPLOYEE. Id is
 * DBMS generated by sequence, should not be provided by caller.
 * 
 * @apiNote the GeneratedValue with strategy GenerationType.SEQUENCE is NOT supported by MySql
 * @see Employee4Car the other side of the one to one relation
 */
@Entity
public class CarBySequence {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CarGen")
    @SequenceGenerator(sequenceName = "CAR_SEQ", allocationSize = 1, name = "CarGen")
    @Column(name = "CAR_ID")
    private Integer id;

    @Column(name = "NAME")
    private String name;

    @OneToOne(optional = true)
    @JoinColumn(name = "EMPLOYEE_ID")
    private Employee4Car employee;

    public CarBySequence() {
    }

    public CarBySequence(String name) {
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Employee4Car getEmployee() {
        return employee;
    }

    public void setEmployee(Employee4Car employee) {
        this.employee = employee;
    }

    @Override
    public String toString() {
        return "Car [id=" + id + ", name=" + name + ", employee=" + employee + "]";
    }
}
