/*
 * Introduction to Hibernate - JEE ORM
 * 
 * https://github.com/egalli64/jeed
 */
package com.example.jeed.m2.s3;

import java.io.IOException;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.example.jeed.dao.Region;
import com.example.jeed.dao.RegionDao;
import com.example.jeed.listener.ContextListener;

/**
 * Create entity by EntityManager::persist() with id generated by DBMS
 * 
 * @see Region entity with id as GeneratedValue following IDENTITY strategy
 * @see RegionDao the DAO that actually does the job
 */
@SuppressWarnings("serial")
@WebServlet("/m2/s3/region/create")
public class RegionCreateServlet extends HttpServlet {
    private static final Logger log = LogManager.getLogger(RegionCreateServlet.class);
    private RegionDao dao;

    @Override
    public void init() throws ServletException {
        dao = (RegionDao) getServletContext().getAttribute(ContextListener.REGION_DAO);
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String name = request.getParameter("name");
        log.traceEntry(name);

        Region region = new Region(name);
        request.setAttribute("message", dao.create(region) ? region : "Can't create region with name " + name);
        request.getRequestDispatcher("/m2/s3/newEntity.jsp").forward(request, response);
    }
}
