/*
 * Introduction to Jakarta Enterprise Edition - JPA on Hibernate
 * 
 * https://github.com/egalli64/jeed
 */
package com.example.jeed.s08;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.example.jeed.dao.Car;
import com.example.jeed.dao.CarDao;
import com.example.jeed.dao.ContextListener;

/**
 * Create entity by EntityManager::persist() with id generated by DBMS
 * 
 * @see Car entity with id as GeneratedValue following SEQUENCE strategy
 * @see CarDao the DAO that actually does the job
 */
@SuppressWarnings("serial")
@WebServlet("/s08/car/create")
public class CarCreateServlet extends HttpServlet {
    private static final Logger log = LogManager.getLogger(CarCreateServlet.class);
    private CarDao dao;

    @Override
    public void init() throws ServletException {
        dao = (CarDao) getServletContext().getAttribute(ContextListener.CAR_DAO);
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String name = request.getParameter("name");
        log.traceEntry(name);

        Car car = new Car(name);
        request.setAttribute("message", dao.create(car) ? car : "Can't create car with name " + name);

        request.getRequestDispatcher("/s08/newEntity.jsp").forward(request, response);
    }
}
